### ISSUE TITLE
Logging Visibility

### ISSUE THREAD

**Issue by tomgco** [numo-labs/taggable-searcher#30]
Currently this module uses `console.log`'s to log out information such as the current `Neo4J` query that is being ran, as well as some other debugging statements.

This has the problem of not allowing the consumer to choose how to display these logs.

Seeming as it shouldn't be the responsibility of this module to log, I am proposing on removing all `console.log` statements and replacing them with the module [debug](https://www.npmjs.com/package/debug) to be used only during development.

The next step would be then to return query information and other useful objects returned by the callbacks, allowing the consumer to implement logging themselves.

For example instead of returning just the result in the body like:

```js
taggy.store.get('geo:geonames.10062607', function (err, result) {
  // result is the result as an object
});
```

instead we could possibly return in:

```js
taggy.store.get('geo:geonames.10062607', function (err, obj) {
  // obj = {
  //    result: { ... },
  //    query: { ... },
  //    ...
  //  }
  // In an error case we would return the error and just the query + extra meta data in the obj.
});
```

Before I implement these changes as a major version bump I was wondering if anyone has any objections to this or have other thoughts on a possible design? Originally I thought of using event emitters, but seeming that this isn't used at all in this module I thought it would be too clunky.

@numo-labs/developers 

Thanks :]

**Comment by nelsonic** [comment]
@tomgco no objections to these changes. 👍
